In [5]:
import pandas as pd

In [6]:
df=pd.read_csv(r'./files/causeofdeath.csv',delimiter=",",encoding="ISO-8859-1")

In [21]:
df_filtered = df[df['Year'] != "2017"]

df.head()

,Location,Year,Age,Sex,Cause of death or injury,Measure,Value,Lower bound,Upper bound
0,Global,2017,All ages,Both,Tuberculosis,Percent of total deaths,0.021157,0.020229,0.022217
1,Global,2005 - 2010,All ages,Both,Tuberculosis,Deaths annual % change,-0.032549,NaN,NaN
2,Global,2017,All ages,Both,HIV/AIDS,Percent of total deaths,0.017061,0.016189,0.018019
3,Global,2005 - 2010,All ages,Both,HIV/AIDS,Deaths annual % change,-0.045663,NaN,NaN
4,Global,2017,All ages,Both,Diarrheal diseases,Percent of total deaths,0.028053,0.021061,0.039013

In [22]:
df_filtered.head()

,Location,Year,Age,Sex,Cause of death or injury,Measure,Value,Lower bound,Upper bound
1,Global,2005 - 2010,All ages,Both,Tuberculosis,Deaths annual % change,-0.032549,NaN,NaN
3,Global,2005 - 2010,All ages,Both,HIV/AIDS,Deaths annual % change,-0.045663,NaN,NaN
5,Global,2005 - 2010,All ages,Both,Diarrheal diseases,Deaths annual % change,-0.019358,NaN,NaN
7,Global,2005 - 2010,All ages,Both,Other intestinal infectious diseases,Deaths annual % change,-0.066309,NaN,NaN
9,Global,2005 - 2010,All ages,Both,Lower respiratory infections,Deaths annual % change,-0.021150,NaN,NaN

In [23]:

df_filtered.to_csv(r'./files/causeofdeath_2005.csv', index=False)